version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: postgres-bot-starter
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
  redis:
    image: redis
    container_name: redis-bot-starter
    restart: always
    ports:
      - 6379:6379